import { isAbsolute, join, normalize } from "node:path";
import type { CommentsConfig } from "./config.ts";
import { isRecord } from "./config.ts";
import { Scanner, type Finding, type Language } from "./patterns.ts";

export interface CheckResult {
  path: string;
  tool: string;
  findings: Finding[];
}

export const PATH_KEYS = ["path", "file_path", "filePath", "file"] as const;
export const CONTENT_KEYS = ["content", "text", "body"] as const;
export const NEW_KEYS = ["newText", "new_string", "newStr", "new_str", "new", "replacement"] as const;
export const OLD_KEYS = ["oldText", "old_string", "oldStr", "old_str", "old"] as const;

export class InputReader {
  stringField(input: Record<string, unknown>, keys: readonly string[]): string | null {
    for (const key of keys) {
      const value = input[key];

      if (typeof value === "string") {
        return value;
      }
    }

    return null;
  }

  isGenerated(content: string): boolean {
    const head = content.split("\n", 5).join("\n");

    return /@generated|code generated by|do not edit|auto-?generated/i.test(head);
  }

  diffAdded(oldText: string, newLines: readonly string[]): boolean[] {
    const counts = new Map<string, number>();

    for (const line of oldText.split("\n")) {
      const key = line.trim();
      counts.set(key, (counts.get(key) ?? 0) + 1);
    }

    return newLines.map((line) => {
      const key = line.trim();
      const remaining = counts.get(key) ?? 0;

      if (remaining > 0) {
        counts.set(key, remaining - 1);
        return false;
      }

      return true;
    });
  }
}

export class PathMatcher {
  private readonly globCache = new Map<string, RegExp | null>();

  matchesIgnore(resolved: string, cwd: string, patterns: readonly string[]): boolean {
    const candidates = this.pathCandidates(resolved, cwd);

    for (const pattern of patterns) {
      if (typeof pattern !== "string" || pattern.trim().length === 0) {
        continue;
      }

      const regex = this.globToRegExp(pattern.replace(/\\/g, "/").replace(/^\.\//, ""));

      if (regex === null) {
        continue;
      }

      if (candidates.some((candidate) => regex.test(candidate))) {
        return true;
      }
    }

    return false;
  }

  private globToRegExp(pattern: string): RegExp | null {
    const cached = this.globCache.get(pattern);

    if (cached !== undefined) {
      return cached;
    }

    let source = "";
    let index = 0;

    while (index < pattern.length) {
      const char = pattern[index];

      if (char === "*") {
        if (pattern[index + 1] === "*") {
          if (pattern[index + 2] === "/") {
            source += "(?:[^/]+/)*";
            index += 3;
          } else {
            source += ".*";
            index += 2;
          }

          continue;
        }

        source += "[^/]*";
        index += 1;
        continue;
      }

      if (char === "?") {
        source += "[^/]";
        index += 1;
        continue;
      }

      source += char.replace(/[.+^${}()|[\]\\]/g, "\\$&");
      index += 1;
    }

    let regex: RegExp | null = null;

    try {
      regex = new RegExp(`^${source}$`);
    } catch {
      regex = null;
    }

    this.globCache.set(pattern, regex);

    return regex;
  }

  private pathCandidates(resolved: string, cwd: string): string[] {
    const norm = resolved
      .replace(/\\/g, "/")
      .replace(/^[A-Za-z]:/, "")
      .replace(/^\/+/, "");
    const candidates = [norm];
    const cwdNorm = cwd
      .replace(/\\/g, "/")
      .replace(/^[A-Za-z]:/, "")
      .replace(/^\/+/, "")
      .replace(/\/+$/, "");

    if (cwdNorm.length > 0 && norm.startsWith(`${cwdNorm}/`)) {
      candidates.push(norm.slice(cwdNorm.length + 1));
    }

    const base = norm.split("/").pop();

    if (base !== undefined && base.length > 0) {
      candidates.push(base);
    }

    return candidates;
  }
}

export class Checker {
  private readonly scanner: Scanner;
  private readonly matcher: PathMatcher;
  private readonly reader: InputReader;

  constructor(scanner: Scanner) {
    this.scanner = scanner;
    this.matcher = new PathMatcher();
    this.reader = new InputReader();
  }

  runCheck(toolName: string, input: unknown, cwd: string, config: CommentsConfig): CheckResult | null {
    if (toolName !== "write" && toolName !== "edit") {
      return null;
    }

    if (!isRecord(input)) {
      return null;
    }

    const rawPath = this.reader.stringField(input, PATH_KEYS);

    if (rawPath === null || rawPath.trim().length === 0) {
      return null;
    }

    const resolved = isAbsolute(rawPath) ? normalize(rawPath) : normalize(join(cwd, rawPath));

    if (this.matchesIgnore(resolved, cwd, config.ignore)) {
      return null;
    }

    let lines: string[];
    let added: boolean[];
    let language: Language | null;

    if (toolName === "write") {
      const content = this.reader.stringField(input, CONTENT_KEYS);

      if (content === null || content.length === 0) {
        return null;
      }

      if (this.reader.isGenerated(content)) {
        return null;
      }

      language = this.scanner.detectLanguage(resolved, content);
      lines = content.split("\n");
      added = lines.map(() => true);
    } else {
      const newText = this.reader.stringField(input, NEW_KEYS);

      if (newText === null || newText.length === 0) {
        return null;
      }

      const oldText = this.reader.stringField(input, OLD_KEYS) ?? "";
      language = this.scanner.detectLanguage(resolved);
      lines = newText.split("\n");
      added = this.reader.diffAdded(oldText, lines);
    }

    if (language === null || language === "md" || language === "json") {
      return null;
    }

    const findings = this.scanner.scanAdded(lines, added, language, {
      allowMarker: config.allowMarker,
      detectors: config.detectors,
    });

    if (findings.length === 0) {
      return null;
    }

    return { path: resolved, tool: toolName, findings };
  }

  matchesIgnore(resolved: string, cwd: string, patterns: readonly string[]): boolean {
    return this.matcher.matchesIgnore(resolved, cwd, patterns);
  }
}
