import { isAbsolute, join, normalize } from "node:path";
import { detectLanguage, scanAdded, type DetectorToggles, type Finding, type Language } from "./patterns.ts";

export type { DetectorToggles, Finding } from "./patterns.ts";

export const MODES = ["block", "warn", "off"] as const;

export type Mode = (typeof MODES)[number];

export interface CommentsConfig {
  mode: Mode;
  maxFindings: number;
  allowMarker: string;
  ignore: string[];
  detectors: DetectorToggles;
}

export interface CheckResult {
  path: string;
  tool: string;
  findings: Finding[];
}

const PATH_KEYS = ["path", "file_path", "filePath", "file"] as const;
const CONTENT_KEYS = ["content", "text", "body"] as const;
const NEW_KEYS = ["newText", "new_string", "newStr", "new_str", "new", "replacement"] as const;
const OLD_KEYS = ["oldText", "old_string", "oldStr", "old_str", "old"] as const;

const globCache = new Map<string, RegExp | null>();

export function isMode(value: unknown): value is Mode {
  return value === "block" || value === "warn" || value === "off";
}

export function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringField(input: Record<string, unknown>, keys: readonly string[]): string | null {
  for (const key of keys) {
    const value = input[key];
    if (typeof value === "string") {
      return value;
    }
  }
  return null;
}

function globToRegExp(pattern: string): RegExp | null {
  const cached = globCache.get(pattern);
  if (cached !== undefined) {
    return cached;
  }
  let source = "";
  let index = 0;
  while (index < pattern.length) {
    const char = pattern[index];
    if (char === "*") {
      if (pattern[index + 1] === "*") {
        if (pattern[index + 2] === "/") {
          source += "(?:[^/]+/)*";
          index += 3;
        } else {
          source += ".*";
          index += 2;
        }
        continue;
      }
      source += "[^/]*";
      index += 1;
      continue;
    }
    if (char === "?") {
      source += "[^/]";
      index += 1;
      continue;
    }
    source += char.replace(/[.+^${}()|[\]\\]/g, "\\$&");
    index += 1;
  }
  let regex: RegExp | null = null;
  try {
    regex = new RegExp(`^${source}$`);
  } catch {
    regex = null;
  }
  globCache.set(pattern, regex);
  return regex;
}

function pathCandidates(resolved: string, cwd: string): string[] {
  const norm = resolved
    .replace(/\\/g, "/")
    .replace(/^[A-Za-z]:/, "")
    .replace(/^\/+/, "");
  const candidates = [norm];
  const cwdNorm = cwd
    .replace(/\\/g, "/")
    .replace(/^[A-Za-z]:/, "")
    .replace(/^\/+/, "")
    .replace(/\/+$/, "");
  if (cwdNorm.length > 0 && norm.startsWith(`${cwdNorm}/`)) {
    candidates.push(norm.slice(cwdNorm.length + 1));
  }
  const base = norm.split("/").pop();
  if (base !== undefined && base.length > 0) {
    candidates.push(base);
  }
  return candidates;
}

export function matchesIgnore(resolved: string, cwd: string, patterns: readonly string[]): boolean {
  const candidates = pathCandidates(resolved, cwd);
  for (const pattern of patterns) {
    if (typeof pattern !== "string" || pattern.trim().length === 0) {
      continue;
    }
    const regex = globToRegExp(pattern.replace(/\\/g, "/").replace(/^\.\//, ""));
    if (regex === null) {
      continue;
    }
    if (candidates.some((candidate) => regex.test(candidate))) {
      return true;
    }
  }
  return false;
}

function isGenerated(content: string): boolean {
  const head = content.split("\n", 5).join("\n");
  return /@generated|code generated by|do not edit|auto-?generated/i.test(head);
}

function diffAdded(oldText: string, newLines: readonly string[]): boolean[] {
  const counts = new Map<string, number>();
  for (const line of oldText.split("\n")) {
    const key = line.trim();
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return newLines.map((line) => {
    const key = line.trim();
    const remaining = counts.get(key) ?? 0;
    if (remaining > 0) {
      counts.set(key, remaining - 1);
      return false;
    }
    return true;
  });
}

export function runCheck(toolName: string, input: unknown, cwd: string, config: CommentsConfig): CheckResult | null {
  if (toolName !== "write" && toolName !== "edit") {
    return null;
  }
  if (!isRecord(input)) {
    return null;
  }
  const rawPath = stringField(input, PATH_KEYS);
  if (rawPath === null || rawPath.trim().length === 0) {
    return null;
  }
  const resolved = isAbsolute(rawPath) ? normalize(rawPath) : normalize(join(cwd, rawPath));
  if (matchesIgnore(resolved, cwd, config.ignore)) {
    return null;
  }
  let lines: string[];
  let added: boolean[];
  let language: Language | null;
  if (toolName === "write") {
    const content = stringField(input, CONTENT_KEYS);
    if (content === null || content.length === 0) {
      return null;
    }
    if (isGenerated(content)) {
      return null;
    }
    language = detectLanguage(resolved, content);
    lines = content.split("\n");
    added = lines.map(() => true);
  } else {
    const newText = stringField(input, NEW_KEYS);
    if (newText === null || newText.length === 0) {
      return null;
    }
    const oldText = stringField(input, OLD_KEYS) ?? "";
    language = detectLanguage(resolved);
    lines = newText.split("\n");
    added = diffAdded(oldText, lines);
  }
  if (language === null || language === "md" || language === "json") {
    return null;
  }
  const findings = scanAdded(lines, added, language, {
    allowMarker: config.allowMarker,
    detectors: config.detectors,
  });
  if (findings.length === 0) {
    return null;
  }
  return { path: resolved, tool: toolName, findings };
}

function clip(text: string): string {
  const flat = text.replace(/\s+/g, " ").trim();
  if (flat.length <= 160) {
    return flat;
  }
  return `${flat.slice(0, 159)}…`;
}

export function formatFindings(findings: readonly Finding[], max: number): string {
  const cap = Math.max(1, Math.floor(max));
  const shown = findings.slice(0, cap);
  const lines = shown.map(
    (finding, index) => `${index + 1}. [${finding.rule}] line ${finding.line}: ${clip(finding.text)} (${finding.message})`,
  );
  const hidden = findings.length - shown.length;
  if (hidden > 0) {
    lines.push(`… ${hidden} more finding${hidden === 1 ? "" : "s"} not shown`);
  }
  return lines.join("\n");
}
